version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: superquizz-db
    environment:
      POSTGRES_DB: superquizz
      POSTGRES_USER: superquizz
      POSTGRES_PASSWORD: superquizz
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U superquizz"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 