spring:
  application:
    name: superquizz
    version: 0.0.1-SNAPSHOT
  datasource:
    url: jdbc:postgresql://localhost:5432/superquizz
    username: superquizz
    password: superquizz
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

# Configuration JWT (à personnaliser)
jwt:
  secret: votre_secret_jwt_a_changer
  expiration: 86400000 # 24 heures en millisecondes 