spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quizapp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

# Configuration JWT (à personnaliser)
jwt:
  secret: votre_secret_jwt_a_changer
  expiration: 86400000 # 24 heures en millisecondes 